name: Build ProxyBlind dylib

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show SDKs
        run: |
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-path

      - name: Build
        run: |
          make clean
          make TARGET=iphoneos ARCHS=arm64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProxyBlind
          path: ProxyBlind.dylib
